uint8 dataID = 29
uint8 ar_tag_1_ID
uint8 ar_tag_2_ID
uint8 ar_tag_3_ID
uint8 ar_tag_4_ID
uint8 ar_tag_5_ID
uint8 ar_tag_6_ID
uint8 ar_tag_7_ID
float32[3] powertrain_pose_position
float32[3] powertrain_pose_orientation
float32[3] visOdom_pose_position
float32[3] visOdom_pose_orientation
float32[3] landmark_pose_position
float32[3] landmark_pose_orientation
ArTag[7] ar_tags
uint8[4] calc_node_states


